### PR TITLE
Fix libraries

### PR DESCRIPTION
**Pull request by jasedit**
Fixing several minor issues, edge cases, and bugs with these libraries. Please review, test, comment, etc.

### CODE REVIEW

**Comment by jasedit** [comment]
@aakruthigopisetty @ningliVT Is there someone who can review this PR and verify it works for you all? These fixes fix several bugs when using sim_weather and time_frame in the House app, so it would be useful to have someone verify these fixes don't break other things in sim_harness before accepting this.

**Comment by aakruthigopisetty** [comment]
Yes, Jason. I will look into it and get back to you as soon as I can.

Thanks,
Aakruthi

**Comment by bt2016** [comment]
I don't see any adverse effects, confirming pull request!

**Comment by aakruthigopisetty** [comment]
There didn't seem to be any problem with these fixes. We have merged it.

Thanks,
Aakruthi

**Comment by jasedit** [comment]
Thanks!

**Pull request merged**
